---
abstract: 'Automatic number guessing game robot'
author:
  - 'imacat <imacat@mail.imacat.idv.tw>'
build_requires:
  Module::Signature: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-GuessNumber
provides:
  Acme::GuessNumber:
    file: lib/Acme/GuessNumber.pm
    version: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
